### ISSUE TITLE
error when basic scraping

### ISSUE THREAD

**Issue by webstandardcss** [pthrasher/cli-scrape#2]
Treys-iMac:~ trey$ scrape http://nautil.us/issue/29/scaling/why-science-needs-metaphysics '.page-content'

```
/usr/local/lib/node_modules/cli-scrape/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cli-scrape/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by pthrasher** [comment]
Very interesting.

I must say I'm a bit surprised as this project is pretty outdated. That said, I didn't realize anyone was really using this! :-)

I'll take a look. Thanks for the feedback.

**Comment by webstandardcss** [comment]
I just found you by googling "scrape html class command line" Here is an alternative that works.

```
echo "http://nautil.us/issue/29/scaling/why-science-needs-metaphysics" |
   wget -O- -i- | 
   # brew install html-xml-utils
   hxnormalize -x | 
   hxselect -i ".page-content" |  
   lynx -stdin -dump > testarticle.txt |
   cat testarticle.txt
```

**Comment by pthrasher** [comment]
@webstandardcss I just pushed an update that will work now. It's live on NPM, so just fetch the latest version, and you should be good to go. :-)

**Comment by webstandardcss** [comment]
Thank you so much, this is so much easier syntax than the alternative. 

I did the following to try to install latest. Did I miss a step.  I get the same error.

```
Treys-iMac:~ trey$ npm uninstall -g cli-scrape
unbuild cli-scrape@0.1.10
Treys-iMac:~ trey$ npm update
Treys-iMac:~ trey$ npm upgrade
Treys-iMac:~ trey$ npm install -g cli-scrape
/usr/local/bin/scrape -> /usr/local/lib/node_modules/cli-scrape/lib/scrape.js
cli-scrape@0.1.10 /usr/local/lib/node_modules/cli-scrape
├── optimist@0.3.7 (wordwrap@0.0.3)
├── npmlog@0.0.2 (ansi@0.1.2)
├── request@2.12.0
└── jsdom@6.5.1 (acorn-globals@1.0.6, xml-name-validator@2.0.1, xtend@4.0.0, xmlhttprequest@1.7.0, browser-request@0.3.3, symbol-tree@3.1.2, cssom@0.3.0, nwmatcher@1.3.6, parse5@1.5.0, whatwg-url-compat@0.6.5, acorn@2.4.0, tough-cookie@2.0.0, htmlparser2@3.8.3, escodegen@1.7.0, request@2.64.0, cssstyle@0.2.29)
```

**Comment by webstandardcss** [comment]
Same error

```
Treys-iMac:~ trey$ scrape http://nautil.us/issue/29/scaling/why-science-needs-metaphysics '.page-content'
/usr/local/lib/node_modules/cli-scrape/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js or Node.js 4 or newer: https://github.co
^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cli-scrape/lib/scrape.js:9:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Treys-iMac:~ trey$
```

**Comment by pthrasher** [comment]
@webstandardcss Oops! 

Looks like you're not yet on nodejs 4.x -- The latest jsdom (which is what I updated to) requires nodejs 4.x. This afternoon I may be able to look into supporting an older version, but for now, you'll have to upgrade to latest node to use this package.
